name: upgraded-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - matplotlib
  - pandas
  - pandas-datareader=0.8.1
  - bokeh
  - pythreejs
  - nodejs
  - jupyterlab=1.0.2
  - scikit-image
  - scikit-learn
  - seaborn
  - tensorflow
  - sympy
  - keras
  - graphviz
  - python-graphviz
  - jsonpickle
  - ipycanvas=0.4.7