channels:
- auto
- bokeh/channel/dev
- conda-forge
- biocore
- bioconda
- edbr
dependencies:
- jupyterlab=0.32.1
- nodejs=8.9
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.8.2
- ipywidgets=7.2
- ipympl=0.2
- widgetsnbextension=3.4
- altair=1.2
- bqplot=0.10
- dask=0.15
- matplotlib=2.2.3
- pandas<=0.23
- python=3.6
- scikit-image>=0.14
- scikit-learn>=0.18
- scikit-bio=0.5.4
- seaborn=0.9
- tensorflow>=1.9
- sympy=1.2
- pyyaml=3.12
- traittypes=0.2
- invoke=1.1.1
- plotly=3.1
- nglview
- ssbio-edbr
- numpy
- tqdm
- six
- slugify
- lxml
- requests>=2.13.0
- biopython>=1.69
- xmltodict
- mmtf-python
- msgpack-python
- awesome-slugify
- beautifulsoup4=4.5.3
- nbsphinx
- biopandas
- scipy
- pytest
- cobra
- more-itertools
- json_tricks>3.0
- bcbio-gff
- bioservices
- deprecation
