channels:
- bokeh/channel/dev 
- conda-forge
- anaconda
dependencies:
- jupyterlab=1.0.2
- nodejs=8.9
- notebook=6.0.1
- nbconvert=5.5.0
- ipykernel=5.1.2
- ipywidgets=7.5.1
- ipympl=0.2
- widgetsnbextension=3.5.1
- altair=1.2
- bqplot=0.10
- dask=0.15
- matplotlib=2.2.3
- pandas=0.23
- python=3.6
- scikit-image=0.14
- scikit-learn=0.18
- seaborn=0.9
- tensorflow=1.9
- sympy=1.2
- pyyaml=5.1.2
- traittypes=0.2.1
- invoke=1.1.1
- plotly=3.1
- pandas-datareader
- keras
- pydotplus
- statsmodels
- graphviz
- python-graphviz
- pythreejs