channels:
- conda-forge
dependencies:
- jupyterlab=0.33.8
- nodejs=8.9
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.8.2
- ipywidgets=7.2
- ipympl=0.2.1
- widgetsnbextension=3.4
- altair=1.2
- bqplot=0.11
- dask=0.18
- matplotlib=2.2.3
- pandas=0.23
- python=3.6
- scikit-image=0.14
- scikit-learn=0.18
- seaborn=0.9
- tensorflow=1.9
- sympy=1.2
- pyyaml=3.12
- traittypes==0.2.1
- invoke=1.1.1
