name: upgraded-environment
channel_priority: strict
channels:
  - conda-forge
  - esri
dependencies:
  - numpy
  - psutil
  - matplotlib
  - pandas
  - pandas-datareader=0.8.1
  - bokeh
  - pythreejs
  - nodejs
  - jupyterlab=1.0.2
  - scikit-image
  - scikit-learn
  - seaborn
  - tensorflow
  - sympy
  - keras
  - graphviz
  - python-graphviz
  - jsonpickle
  - conda-forge::chainladder
  - conda-forge::pyshp
  - conda-forge::Shapely
  - conda-forge::folium
  - conda-forge::geojson
  - conda-forge::geopandas
  - conda-forge::libgdal
  - conda-forge::gdal
  - esri::arcgis